### PR TITLE
Created carousel for sponsors and partners

### PR DESCRIPTION
**Pull request by kinyuykelly**
Screenshot from 2023-10-09 18-14-27
Screenshot from 2023-10-09 18-50-23
#5

### CODE REVIEW

**Review by Idadelveloper — CHANGES_REQUESTED** [review]
@Kinyuykelly there's a convention we are using when naming the files and folders of the codes in the src file of this react project. It should be `Partners/Partners.jsx` and `Partners/Partners.css` not `partners/partners.jsx` and `partners/partners.css`

**Comment by kinyuykelly** [comment]
Okay

**Comment by kinyuykelly** [comment]
@Idadelveloper I have amended the commit

**Review by Idadelveloper — APPROVED** [review]

**Comment by Idadelveloper** [comment]
Thank you @Kinyuykelly for solving #5

**Pull request merged**
