### PR TITLE
(FE #7) Created card component to display ambassadors and organizers

### LINKED ISSUE #7: Create card component to display ambassadors and organizers
Refer to the [about page of the design](https://www.figma.com/file/FHiXmUWupq9y5M5Um0BFKq/UI?type=design&node-id=122-389&mode=design&t=6UrItohE94JPA2Yi-0) and create a card that contains:
- Person's image
- Occupation
- Social links

### PR DESCRIPTION
**Pull request by shenyuygoodness**
(fixes #7) Created the card component which displays the ambassadors and organizers with their names, jobs, and social media links

### CODE REVIEW

**Comment by Idadelveloper** [comment]
@shenyuygoodness can you comment with a screenshot?

**Comment by shenyuygoodness** [comment]
Screenshot from 2023-10-08 19-29-02

This is it

**Review by Idadelveloper — CHANGES_REQUESTED** [review]
@shenyuygoodness we want just a single card component for this which will accept props with the ambassador/organizer info. That way we can easily reuse it and we won't have to repeat code. The props it should accept should include dynamic info like their name, link to image asset, social links, etc

So the Card.jsx file should represent just a single card that can be reused on the about page. It's on the about page that we will make use of this component and display all ambassadors and organizers.

**Comment by shenyuygoodness** [comment]
Screenshot from 2023-10-17 16-18-12

@Idadelveloper  I have made the necessary changes.

**Review by Idadelveloper — CHANGES_REQUESTED** [review]
@shenyuygoodness please remove the changes you made in index.js

**Review by Idadelveloper — APPROVED** [review]
LGTM!!!

**Pull request merged**
